# Generated by Django 4.2.7 on 2023-11-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255, unique=True)),
                ('last_processed_position', models.PositiveIntegerField(default=0)),
                ('last_modified', models.DateTimeField(null=True)),
            ],
        ),
    ]
